trigger:
- master

variables:
  OPENSHIFT_URL: '$(OPENSHIFT_URL)'         # URL del cluster OpenShift
  OPENSHIFT_TOKEN: '$(OPENSHIFT_TOKEN)'     # Variable secreta
  OPENSHIFT_NAMESPACE: '$(OPENSHIFT_NAMESPACE)'  # Proyecto en OpenShift

stages:
- stage: Login
  displayName: 'Login en OpenShift'
  jobs:
  - job: LoginJob
    pool:
      name: Local Agent
    steps:
    - script: |
        oc login $(OPENSHIFT_URL) --token=$(OPENSHIFT_TOKEN) --insecure-skip-tls-verify
        oc project $(OPENSHIFT_NAMESPACE)
      displayName: 'Autenticarse en OpenShift'

- stage: Deploy
  displayName: 'Desplegar Aplicación'
  dependsOn: Login
  jobs:
  - job: DeployJob
    pool:
      name: Local Agent
    steps:
    - script: |
        if oc get dc nodejs-ex >/dev/null 2>&1; then
          echo "La app ya existe, no se ejecuta 'oc new-app'."
        else
          echo "La app no existe, creando..."
          oc new-app https://github.com/rcarneironet/nodejs-ex -l name=vssummit-app
        fi
      displayName: 'Crear nueva app solo si no existe'
    - script: |
        oc start-build nodejs-ex --follow
      displayName: 'Iniciar build'

- stage: Expose
  displayName: 'Exponer Servicio'
  dependsOn: Deploy
  jobs:
  - job: ExposeJob
    pool:
      name: Local Agent
    steps:
    - script: |
        oc expose svc nodejs-ex
      displayName: 'Exponer el servicio a Internet'

- stage: Verify
  displayName: 'Verificar despliegue'
  dependsOn: Expose
  jobs:
  - job: StatusJob
    pool:
      name: Local Agent
    steps:
    - script: |
        oc status
      displayName: 'Ver estado del despliegue'
