trigger:
- master

variables:
  OPENSHIFT_URL: '$(OPENSHIFT_URL)'           # URL del clúster
  OPENSHIFT_TOKEN: '$(OPENSHIFT_TOKEN)'       # Variable secreta
  OPENSHIFT_NAMESPACE: '$(OPENSHIFT_NAMESPACE)'  # Proyecto/namespaces en OpenShift

stages:
- stage: Login
  displayName: 'Login en OpenShift'
  jobs:
  - job: LoginJob
    pool:
      name: Local Agent
    steps:
    - script: |
        oc login $(OPENSHIFT_URL) --token=$(OPENSHIFT_TOKEN) --insecure-skip-tls-verify
        oc project $(OPENSHIFT_NAMESPACE)
      displayName: 'Autenticarse en OpenShift'

- stage: Deploy
  displayName: 'Desplegar Aplicación .NET'
  dependsOn: Login
  jobs:
  - job: DeployJob
    pool:
      name: Local Agent
    steps:
    - script: |
        if oc get dc dotnet >/dev/null 2>&1; then
          echo "La app ya existe, no se ejecuta 'oc new-app'."
        else
          echo "La app no existe, creando..."
          oc new-app --name=dotnet 'dotnet:latest~https://github.com/redhat-developer/s2i-dotnetcore-ex#dotnet-8.0' \
            --build-env DOTNET_STARTUP_PROJECT=app
        fi
      displayName: 'Crear nueva app solo si no existe'

- stage: Expose
  displayName: 'Exponer Servicio y Aplicar TLS'
  dependsOn: Deploy
  jobs:
  - job: ExposeJob
    pool:
      name: Local Agent
    steps:
    - script: |
        oc expose svc dotnet
      displayName: 'Exponer el servicio'
    - script: |
        oc patch route dotnet -p '{"spec":{"tls":{"termination":"edge","insecureEdgeTerminationPolicy":"Redirect"}}}'
      displayName: 'Aplicar TLS tipo Edge'

- stage: Verify
  displayName: 'Verificar Despliegue'
  dependsOn: Expose
  jobs:
  - job: VerifyJob
    pool:
      name: Local Agent
    steps:
    - script: |
        oc status
      displayName: 'Ver estado del despliegue'
